// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/satriahrh/adam-smith/ent/runtime.go

const (
	Version = "v0.5.2"                                          // Version of ent codegen.
	Sum     = "h1:xImCaExB+bZtS6/pSCsjAJ4ShiS9PnQNtP4LedCZj64=" // Sum of ent codegen.
)
