// Code generated by entc, DO NOT EDIT.

package outboundtransaction

import (
	"fmt"
)

const (
	// Label holds the string label denoting the outboundtransaction type in the database.
	Label = "outbound_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldInvoice holds the string denoting the invoice field in the database.
	FieldInvoice = "invoice"
	// FieldBenefit holds the string denoting the benefit field in the database.
	FieldBenefit = "benefit"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"

	// EdgeShipping holds the string denoting the shipping edge name in mutations.
	EdgeShipping = "shipping"
	// EdgeDeals holds the string denoting the deals edge name in mutations.
	EdgeDeals = "deals"

	// Table holds the table name of the outboundtransaction in the database.
	Table = "outbound_transactions"
	// ShippingTable is the table the holds the shipping relation/edge. The primary key declared below.
	ShippingTable = "outbound_transaction_shipping"
	// ShippingInverseTable is the table name for the OutboundShipping entity.
	// It exists in this package in order to avoid circular dependency with the "outboundshipping" package.
	ShippingInverseTable = "outbound_shippings"
	// DealsTable is the table the holds the deals relation/edge. The primary key declared below.
	DealsTable = "outbound_transaction_deals"
	// DealsInverseTable is the table name for the OutboundDeal entity.
	// It exists in this package in order to avoid circular dependency with the "outbounddeal" package.
	DealsInverseTable = "outbound_deals"
)

// Columns holds all SQL columns for outboundtransaction fields.
var Columns = []string{
	FieldID,
	FieldChannel,
	FieldInvoice,
	FieldBenefit,
	FieldCost,
	FieldAmount,
}

var (
	// ShippingPrimaryKey and ShippingColumn2 are the table columns denoting the
	// primary key for the shipping relation (M2M).
	ShippingPrimaryKey = []string{"outbound_transaction_id", "outbound_shipping_id"}
	// DealsPrimaryKey and DealsColumn2 are the table columns denoting the
	// primary key for the deals relation (M2M).
	DealsPrimaryKey = []string{"outbound_transaction_id", "outbound_deal_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Channel defines the type for the channel enum field.
type Channel string

// Channel values.
const (
	ChannelShopee Channel = "shopee"
	ChannelDirect Channel = "direct"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelShopee, ChannelDirect:
		return nil
	default:
		return fmt.Errorf("outboundtransaction: invalid enum value for channel field: %q", c)
	}
}
