// Code generated by entc, DO NOT EDIT.

package product

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescriptions holds the string denoting the descriptions field in the database.
	FieldDescriptions = "descriptions"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldMarketplaces holds the string denoting the marketplaces field in the database.
	FieldMarketplaces = "marketplaces"

	// EdgeVariations holds the string denoting the variations edge name in mutations.
	EdgeVariations = "variations"
	// EdgeBrand holds the string denoting the brand edge name in mutations.
	EdgeBrand = "brand"

	// Table holds the table name of the product in the database.
	Table = "products"
	// VariationsTable is the table the holds the variations relation/edge. The primary key declared below.
	VariationsTable = "product_variations"
	// VariationsInverseTable is the table name for the Variation entity.
	// It exists in this package in order to avoid circular dependency with the "variation" package.
	VariationsInverseTable = "variations"
	// BrandTable is the table the holds the brand relation/edge.
	BrandTable = "products"
	// BrandInverseTable is the table name for the Brand entity.
	// It exists in this package in order to avoid circular dependency with the "brand" package.
	BrandInverseTable = "brands"
	// BrandColumn is the table column denoting the brand relation/edge.
	BrandColumn = "brand_products"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldSku,
	FieldName,
	FieldDescriptions,
	FieldImages,
	FieldMarketplaces,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Product type.
var ForeignKeys = []string{
	"brand_products",
}

var (
	// VariationsPrimaryKey and VariationsColumn2 are the table columns denoting the
	// primary key for the variations relation (M2M).
	VariationsPrimaryKey = []string{"product_id", "variation_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
