// Code generated by entc, DO NOT EDIT.

package product

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescriptions holds the string denoting the descriptions field in the database.
	FieldDescriptions = "descriptions"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldMarketplaces holds the string denoting the marketplaces field in the database.
	FieldMarketplaces = "marketplaces"
	// FieldPrices holds the string denoting the prices field in the database.
	FieldPrices = "prices"
	// FieldStocks holds the string denoting the stocks field in the database.
	FieldStocks = "stocks"

	// EdgeBrand holds the string denoting the brand edge name in mutations.
	EdgeBrand = "brand"

	// Table holds the table name of the product in the database.
	Table = "products"
	// BrandTable is the table the holds the brand relation/edge. The primary key declared below.
	BrandTable = "brand_products"
	// BrandInverseTable is the table name for the Brand entity.
	// It exists in this package in order to avoid circular dependency with the "brand" package.
	BrandInverseTable = "brands"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescriptions,
	FieldImages,
	FieldMarketplaces,
	FieldPrices,
	FieldStocks,
}

var (
	// BrandPrimaryKey and BrandColumn2 are the table columns denoting the
	// primary key for the brand relation (M2M).
	BrandPrimaryKey = []string{"brand_id", "product_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
