// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// BrandsColumns holds the columns for the "brands" table.
	BrandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// BrandsTable holds the schema information for the "brands" table.
	BrandsTable = &schema.Table{
		Name:        "brands",
		Columns:     BrandsColumns,
		PrimaryKey:  []*schema.Column{BrandsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// OutboundDealsColumns holds the columns for the "outbound_deals" table.
	OutboundDealsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quantity", Type: field.TypeUint},
		{Name: "amount", Type: field.TypeUint},
	}
	// OutboundDealsTable holds the schema information for the "outbound_deals" table.
	OutboundDealsTable = &schema.Table{
		Name:        "outbound_deals",
		Columns:     OutboundDealsColumns,
		PrimaryKey:  []*schema.Column{OutboundDealsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// OutboundShippingsColumns holds the columns for the "outbound_shippings" table.
	OutboundShippingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "courier", Type: field.TypeEnum, Enums: []string{"self", "jnt", "shopee_express", "jne", "sicepat", "ninja_express", "anteraja", "pos_indonesia"}},
		{Name: "courier_tracking_code", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"pick", "drop"}},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"requested", "sent", "delivered", "finish"}},
		{Name: "consignee", Type: field.TypeString},
		{Name: "consignee_phone", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "postal_code", Type: field.TypeUint},
		{Name: "cost", Type: field.TypeUint},
	}
	// OutboundShippingsTable holds the schema information for the "outbound_shippings" table.
	OutboundShippingsTable = &schema.Table{
		Name:        "outbound_shippings",
		Columns:     OutboundShippingsColumns,
		PrimaryKey:  []*schema.Column{OutboundShippingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// OutboundTransactionsColumns holds the columns for the "outbound_transactions" table.
	OutboundTransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel", Type: field.TypeEnum, Enums: []string{"shopee", "direct"}},
		{Name: "invoice", Type: field.TypeJSON},
		{Name: "benefit", Type: field.TypeJSON},
		{Name: "cost", Type: field.TypeJSON},
		{Name: "amount", Type: field.TypeUint},
	}
	// OutboundTransactionsTable holds the schema information for the "outbound_transactions" table.
	OutboundTransactionsTable = &schema.Table{
		Name:        "outbound_transactions",
		Columns:     OutboundTransactionsColumns,
		PrimaryKey:  []*schema.Column{OutboundTransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sku", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "descriptions", Type: field.TypeJSON},
		{Name: "images", Type: field.TypeJSON},
		{Name: "marketplaces", Type: field.TypeJSON},
		{Name: "brand_products", Type: field.TypeInt, Nullable: true},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "products_brands_products",
				Columns: []*schema.Column{ProductsColumns[6]},

				RefColumns: []*schema.Column{BrandsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// VariantsColumns holds the columns for the "variants" table.
	VariantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"color", "size"}},
		{Name: "value", Type: field.TypeString},
	}
	// VariantsTable holds the schema information for the "variants" table.
	VariantsTable = &schema.Table{
		Name:        "variants",
		Columns:     VariantsColumns,
		PrimaryKey:  []*schema.Column{VariantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "variant_value",
				Unique:  false,
				Columns: []*schema.Column{VariantsColumns[2]},
			},
		},
	}
	// VariationsColumns holds the columns for the "variations" table.
	VariationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "images", Type: field.TypeJSON, Nullable: true},
		{Name: "stock", Type: field.TypeUint8},
		{Name: "price", Type: field.TypeUint},
		{Name: "product_variations", Type: field.TypeInt, Nullable: true},
		{Name: "variation_children", Type: field.TypeInt, Nullable: true},
	}
	// VariationsTable holds the schema information for the "variations" table.
	VariationsTable = &schema.Table{
		Name:       "variations",
		Columns:    VariationsColumns,
		PrimaryKey: []*schema.Column{VariationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "variations_products_variations",
				Columns: []*schema.Column{VariationsColumns[4]},

				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "variations_variations_children",
				Columns: []*schema.Column{VariationsColumns[5]},

				RefColumns: []*schema.Column{VariationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OutboundTransactionShippingColumns holds the columns for the "outbound_transaction_shipping" table.
	OutboundTransactionShippingColumns = []*schema.Column{
		{Name: "outbound_transaction_id", Type: field.TypeInt},
		{Name: "outbound_shipping_id", Type: field.TypeInt},
	}
	// OutboundTransactionShippingTable holds the schema information for the "outbound_transaction_shipping" table.
	OutboundTransactionShippingTable = &schema.Table{
		Name:       "outbound_transaction_shipping",
		Columns:    OutboundTransactionShippingColumns,
		PrimaryKey: []*schema.Column{OutboundTransactionShippingColumns[0], OutboundTransactionShippingColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "outbound_transaction_shipping_outbound_transaction_id",
				Columns: []*schema.Column{OutboundTransactionShippingColumns[0]},

				RefColumns: []*schema.Column{OutboundTransactionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "outbound_transaction_shipping_outbound_shipping_id",
				Columns: []*schema.Column{OutboundTransactionShippingColumns[1]},

				RefColumns: []*schema.Column{OutboundShippingsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// OutboundTransactionDealsColumns holds the columns for the "outbound_transaction_deals" table.
	OutboundTransactionDealsColumns = []*schema.Column{
		{Name: "outbound_transaction_id", Type: field.TypeInt},
		{Name: "outbound_deal_id", Type: field.TypeInt},
	}
	// OutboundTransactionDealsTable holds the schema information for the "outbound_transaction_deals" table.
	OutboundTransactionDealsTable = &schema.Table{
		Name:       "outbound_transaction_deals",
		Columns:    OutboundTransactionDealsColumns,
		PrimaryKey: []*schema.Column{OutboundTransactionDealsColumns[0], OutboundTransactionDealsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "outbound_transaction_deals_outbound_transaction_id",
				Columns: []*schema.Column{OutboundTransactionDealsColumns[0]},

				RefColumns: []*schema.Column{OutboundTransactionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "outbound_transaction_deals_outbound_deal_id",
				Columns: []*schema.Column{OutboundTransactionDealsColumns[1]},

				RefColumns: []*schema.Column{OutboundDealsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// VariantVariantUsesColumns holds the columns for the "variant_variant_uses" table.
	VariantVariantUsesColumns = []*schema.Column{
		{Name: "variant_id", Type: field.TypeInt},
		{Name: "variation_id", Type: field.TypeInt},
	}
	// VariantVariantUsesTable holds the schema information for the "variant_variant_uses" table.
	VariantVariantUsesTable = &schema.Table{
		Name:       "variant_variant_uses",
		Columns:    VariantVariantUsesColumns,
		PrimaryKey: []*schema.Column{VariantVariantUsesColumns[0], VariantVariantUsesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "variant_variant_uses_variant_id",
				Columns: []*schema.Column{VariantVariantUsesColumns[0]},

				RefColumns: []*schema.Column{VariantsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "variant_variant_uses_variation_id",
				Columns: []*schema.Column{VariantVariantUsesColumns[1]},

				RefColumns: []*schema.Column{VariationsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// VariationOutboundDealsColumns holds the columns for the "variation_outbound_deals" table.
	VariationOutboundDealsColumns = []*schema.Column{
		{Name: "variation_id", Type: field.TypeInt},
		{Name: "outbound_deal_id", Type: field.TypeInt},
	}
	// VariationOutboundDealsTable holds the schema information for the "variation_outbound_deals" table.
	VariationOutboundDealsTable = &schema.Table{
		Name:       "variation_outbound_deals",
		Columns:    VariationOutboundDealsColumns,
		PrimaryKey: []*schema.Column{VariationOutboundDealsColumns[0], VariationOutboundDealsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "variation_outbound_deals_variation_id",
				Columns: []*schema.Column{VariationOutboundDealsColumns[0]},

				RefColumns: []*schema.Column{VariationsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "variation_outbound_deals_outbound_deal_id",
				Columns: []*schema.Column{VariationOutboundDealsColumns[1]},

				RefColumns: []*schema.Column{OutboundDealsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BrandsTable,
		OutboundDealsTable,
		OutboundShippingsTable,
		OutboundTransactionsTable,
		ProductsTable,
		VariantsTable,
		VariationsTable,
		OutboundTransactionShippingTable,
		OutboundTransactionDealsTable,
		VariantVariantUsesTable,
		VariationOutboundDealsTable,
	}
)

func init() {
	ProductsTable.ForeignKeys[0].RefTable = BrandsTable
	VariationsTable.ForeignKeys[0].RefTable = ProductsTable
	VariationsTable.ForeignKeys[1].RefTable = VariationsTable
	OutboundTransactionShippingTable.ForeignKeys[0].RefTable = OutboundTransactionsTable
	OutboundTransactionShippingTable.ForeignKeys[1].RefTable = OutboundShippingsTable
	OutboundTransactionDealsTable.ForeignKeys[0].RefTable = OutboundTransactionsTable
	OutboundTransactionDealsTable.ForeignKeys[1].RefTable = OutboundDealsTable
	VariantVariantUsesTable.ForeignKeys[0].RefTable = VariantsTable
	VariantVariantUsesTable.ForeignKeys[1].RefTable = VariationsTable
	VariationOutboundDealsTable.ForeignKeys[0].RefTable = VariationsTable
	VariationOutboundDealsTable.ForeignKeys[1].RefTable = OutboundDealsTable
}
