// Code generated by entc, DO NOT EDIT.

package variation

const (
	// Label holds the string label denoting the variation type in the database.
	Label = "variation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldStock holds the string denoting the stock field in the database.
	FieldStock = "stock"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"

	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeVariant holds the string denoting the variant edge name in mutations.
	EdgeVariant = "variant"
	// EdgeOutboundDeals holds the string denoting the outbound_deals edge name in mutations.
	EdgeOutboundDeals = "outbound_deals"

	// Table holds the table name of the variation in the database.
	Table = "variations"
	// ParentTable is the table the holds the parent relation/edge.
	ParentTable = "variations"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "variation_children"
	// ChildrenTable is the table the holds the children relation/edge.
	ChildrenTable = "variations"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "variation_children"
	// ProductTable is the table the holds the product relation/edge.
	ProductTable = "variations"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_variations"
	// VariantTable is the table the holds the variant relation/edge. The primary key declared below.
	VariantTable = "variant_variations"
	// VariantInverseTable is the table name for the Variant entity.
	// It exists in this package in order to avoid circular dependency with the "variant" package.
	VariantInverseTable = "variants"
	// OutboundDealsTable is the table the holds the outbound_deals relation/edge. The primary key declared below.
	OutboundDealsTable = "variation_outbound_deals"
	// OutboundDealsInverseTable is the table name for the OutboundDeal entity.
	// It exists in this package in order to avoid circular dependency with the "outbounddeal" package.
	OutboundDealsInverseTable = "outbound_deals"
)

// Columns holds all SQL columns for variation fields.
var Columns = []string{
	FieldID,
	FieldImages,
	FieldStock,
	FieldPrice,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Variation type.
var ForeignKeys = []string{
	"product_variations",
	"variation_children",
}

var (
	// VariantPrimaryKey and VariantColumn2 are the table columns denoting the
	// primary key for the variant relation (M2M).
	VariantPrimaryKey = []string{"variant_id", "variation_id"}
	// OutboundDealsPrimaryKey and OutboundDealsColumn2 are the table columns denoting the
	// primary key for the outbound_deals relation (M2M).
	OutboundDealsPrimaryKey = []string{"variation_id", "outbound_deal_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStock holds the default value on creation for the stock field.
	DefaultStock uint8
	// DefaultPrice holds the default value on creation for the price field.
	DefaultPrice uint
)
