// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/satriahrh/adam-smith/ent/brand"
	"github.com/satriahrh/adam-smith/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescName is the schema descriptor for name field.
	brandDescName := brandFields[0].Descriptor()
	// brand.NameValidator is a validator for the "name" field. It is called by the builders before save.
	brand.NameValidator = brandDescName.Validators[0].(func(string) error)
}
