name: 'Test'
on: push
jobs:
  migration:
    name: 'MySQL Database Migration'
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: rootpw
          MYSQL_DATABASE: adam_smith
        ports:
          - 3306
      goose:
        image: artsafin/goose-migrations
    env:
      DATABASE_MYSQL_DBSTRING: root:rootpw@tcp(127:0:0:1:3306)/adam_smith?parseTime=true
    steps:
      - uses: actions/checkout@v2
      - name: 'Migrate the DB'
        run: |
          make goose up
      - name: 'Dump the migration status'
        run: |
          make goose status
