name: 'Test'
on: push
jobs:
  migration:
    name: 'MySQL Database Migration'
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: adam_smith
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: 'Setup'
        run: |
          make setup
      - name: 'Migrate the DB'
        run: |
          make goose up
        env:
          DATABASE_MYSQL_HOST: ${{ job.services.mysql.ports[3306] }}
          DATABASE_MYSQL_DBSTRING: root:rootpw@tcp(127.0.0.1:${DATABASE_MYSQL_HOST})/adam_smith?parseTime=true
      - name: 'Dump the migration status'
        run: |
          make goose status
        env:
          DATABASE_MYSQL_HOST: ${{ job.services.mysql.ports[3306] }}
          DATABASE_MYSQL_DBSTRING: root:rootpw@tcp(127.0.0.1:${DATABASE_MYSQL_HOST})/adam_smith?parseTime=true
