name: Test
on: push
jobs:
  go-vet:
    name: Go Vet
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup
        run: |
          make setup
      - name: The vet
        run: |
          go list ./... | grep -v build | xargs go vet -v
  go-test:
    name: Go Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup
        run: |
          make setup
      - name: The Test
        run: |
          make test
      - name: Upload Coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
