name: 'Test'
on: push
jobs:
  migration:
    name: 'MySQL Database Migration'
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: rootpw
          MYSQL_DATABASE: adam_smith
    env:
      DATABASE_MYSQL_DBSTRING: root:rootpw@tcp(mysql:${{ job.services.mysql.ports['3306'] }})/adam_smith?parseTime=true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: 'Setup'
        run: |
          make setup
      - name: 'Migrate the DB'
        run: |
          make goose up
      - name: 'Dump the migration status'
        run: |
          make goose status
