// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)
