// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Brand is the predicate function for brand builders.
type Brand func(*sql.Selector)

// OutboundDeal is the predicate function for outbounddeal builders.
type OutboundDeal func(*sql.Selector)

// OutboundShipping is the predicate function for outboundshipping builders.
type OutboundShipping func(*sql.Selector)

// OutboundTransaction is the predicate function for outboundtransaction builders.
type OutboundTransaction func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Variant is the predicate function for variant builders.
type Variant func(*sql.Selector)

// Variation is the predicate function for variation builders.
type Variation func(*sql.Selector)
